name: Search Updater 
run-name: Update Search D1 (#${{ github.run_number }})
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    working-directory: polysearch

jobs:
  process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [ahk, ahp]

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Deno
        uses: denoland/setup-deno@v1.3.0
        with:
          deno-version: v1.x.x
      - name: Pamp it
        env:
          CHAIN: ${{ matrix.chain }}
        run: |
          deno task start
      - name: Execute changes
        if: ${{ hashFiles(matrix.chain) != '' }}
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "polysearch"
          command: d1 execute multisearch --file=./${{ matrix.chain }}
